/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    _DataTableColumnImpl: typeof import('./../options_ui/components/basic/DataTable/_DataTableColumnImpl.vue')['default']
    _DataTableInfer: typeof import('./../options_ui/components/basic/DataTable/_DataTableInfer.vue')['default']
    ArchiveLink: typeof import('./../options_ui/components/basic/ArchiveLink.vue')['default']
    ArchivePreferenceLink: typeof import('./../options_ui/components/basic/ArchivePreferenceLink.vue')['default']
    Button: typeof import('./../options_ui/components/basic/Button.vue')['default']
    ColorInput: typeof import('./../options_ui/components/basic/ColorInput.vue')['default']
    Dialog: typeof import('./../options_ui/components/basic/Dialog/Dialog.vue')['default']
    DialogContent: typeof import('./../options_ui/components/basic/Dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./../options_ui/components/basic/Dialog/DialogDescription.vue')['default']
    DialogDetachedTrigger: typeof import('./../options_ui/components/basic/Dialog/DialogDetachedTrigger.vue')['default']
    DialogTitle: typeof import('./../options_ui/components/basic/Dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./../options_ui/components/basic/Dialog/DialogTrigger.vue')['default']
    DropdownMenu: typeof import('./../options_ui/components/basic/Dropdown/DropdownMenu.vue')['default']
    DropdownMenuContent: typeof import('./../options_ui/components/basic/Dropdown/DropdownMenuContent.vue')['default']
    DropdownMenuItem: typeof import('./../options_ui/components/basic/Dropdown/DropdownMenuItem.vue')['default']
    DropdownMenuTrigger: typeof import('./../options_ui/components/basic/Dropdown/DropdownMenuTrigger.vue')['default']
    Input: typeof import('./../options_ui/components/basic/Input.vue')['default']
    NumberInput: typeof import('./../options_ui/components/basic/NumberInput.vue')['default']
    OptionCategory: typeof import('./../options_ui/components/OptionCategory.vue')['default']
    OptionDivider: typeof import('./../options_ui/components/options/OptionDivider.vue')['default']
    OptionForceAlignment: typeof import('./../options_ui/components/options/OptionForceAlignment.vue')['default']
    OptionHideReason: typeof import('./../options_ui/components/options/OptionHideReason.vue')['default']
    OptionLanguage: typeof import('./../options_ui/components/options/OptionLanguage.vue')['default']
    OptionRow: typeof import('./../options_ui/components/option_rows/OptionRow.vue')['default']
    OptionRowCollapsable: typeof import('./../options_ui/components/option_rows/OptionRowCollapsable.vue')['default']
    OptionRowFandomExport: typeof import('./../options_ui/components/option_rows/OptionRowFandomExport.vue')['default']
    OptionRowHideAuthors: typeof import('./../options_ui/components/option_rows/OptionRowHideAuthors.vue')['default']
    OptionRowHideAuthorsEditDialog: typeof import('./../options_ui/components/option_rows/OptionRowHideAuthorsEditDialog.vue')['default']
    OptionRowHideAuthorsTable: typeof import('./../options_ui/components/option_rows/OptionRowHideAuthorsTable.vue')['default']
    OptionRowHideCrossovers: typeof import('./../options_ui/components/option_rows/OptionRowHideCrossovers.vue')['default']
    OptionRowHideEntities: typeof import('./../options_ui/components/option_rows/OptionRowHideEntities.vue')['default']
    OptionRowHideLanguages: typeof import('./../options_ui/components/option_rows/OptionRowHideLanguages.vue')['default']
    OptionRowHideTags: typeof import('./../options_ui/components/option_rows/OptionRowHideTags.vue')['default']
    OptionRowHideTagsEditDialog: typeof import('./../options_ui/components/option_rows/OptionRowHideTagsEditDialog.vue')['default']
    OptionRowHideTagsTable: typeof import('./../options_ui/components/option_rows/OptionRowHideTagsTable.vue')['default']
    OptionRowImportExport: typeof import('./../options_ui/components/option_rows/OptionRowImportExport.vue')['default']
    OptionRowNumberSlider: typeof import('./../options_ui/components/option_rows/OptionRowNumberSlider.vue')['default']
    OptionRowSearchLanguage: typeof import('./../options_ui/components/option_rows/OptionRowSearchLanguage.vue')['default']
    OptionRowTextReplacements: typeof import('./../options_ui/components/option_rows/OptionRowTextReplacements.vue')['default']
    OptionRowWorkMarks: typeof import('./../options_ui/components/option_rows/OptionRowWorkMarks.vue')['default']
    OptionSearchLanguage: typeof import('./../options_ui/components/options/OptionSearchLanguage.vue')['default']
    OptionSearchPerPage: typeof import('./../options_ui/components/options/OptionSearchPerPage.vue')['default']
    OptionsUIFooter: typeof import('./../options_ui/components/OptionsUIFooter.vue')['default']
    OptionsUIHeader: typeof import('./../options_ui/components/OptionsUIHeader.vue')['default']
    OptionSwitch: typeof import('./../options_ui/components/options/OptionSwitch.vue')['default']
    OptionTheme: typeof import('./../options_ui/components/options/OptionTheme.vue')['default']
    RadioBox: typeof import('./../options_ui/components/basic/RadioBox/RadioBox.vue')['default']
    RadioBoxItem: typeof import('./../options_ui/components/basic/RadioBox/RadioBoxItem.vue')['default']
    RekaTooltipProvider: typeof import('reka-ui')['TooltipProvider']
    Render: typeof import('./../options_ui/components/basic/Render.vue')['default']
    Select: typeof import('./../options_ui/components/basic/Select/Select.vue')['default']
    SelectItem: typeof import('./../options_ui/components/basic/Select/SelectItem.vue')['default']
    Slider: typeof import('./../options_ui/components/basic/Slider.vue')['default']
    Switch: typeof import('./../options_ui/components/basic/Switch.vue')['default']
    SyncBackupsDialog: typeof import('./../options_ui/components/sync/SyncBackupsDialog.vue')['default']
    SyncStorageUsage: typeof import('./../options_ui/components/sync/SyncStorageUsage.vue')['default']
    Tooltip: typeof import('./../options_ui/components/basic/Tooltip.vue')['default']
  }
}
